### ISSUE TITLE
请问怎么查看日志？

### ISSUE THREAD

**Issue by Anivie** [WuXiaoMuer/StartupTools#1]
点击测试时启动正常，但是系统启动后没有如约执行任务，在哪里看错误原因呢

**Comment by WuXiaoMuer** [comment]
可能是UAC的问题导致在注册表中的程序无法如约启动，目前有两种办法😁；
1.解决掉UAC，项目编译提供了有无UAC两种版本。
2.在程序中将程序添加至目录启动。🥰
另一种可能就是杀毒软件，不过我想正经人应该都能解决这种问题。🤗
